<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="railroadmodel" nsURI="http://hu.bme.mit.kv.railroadmodel" nsPrefix="railroadmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Trackable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbours" upperBound="2"
        eType="#//Trackable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" eSuperTypes="#//Trackable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" eType="#//Line"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Trackable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rectangle" lowerBound="1"
        eType="#//Rectangle" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Train">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previouslyOn" eType="#//Trackable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyOn" eType="#//Trackable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Powerable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" lowerBound="1"
        upperBound="-1" eType="#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SectionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="powerables" upperBound="-1"
        eType="#//Powerable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trackables" upperBound="-1"
        eType="#//Trackable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TrainModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trains" upperBound="-1"
        eType="#//Train" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Point"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Point"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle">
    <eOperations name="isPointInside" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="p" eType="#//Point"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin" lowerBound="1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" lowerBound="1" eType="#//Dimension"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverseMatrix" unique="false"
        upperBound="6" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eOperations name="distanceFrom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eParameters name="p" eType="#//Point"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
</ecore:EPackage>
