<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pathfindermodel" nsURI="http://hu.bme.mit.kv.pathfindermodel"
    nsPrefix="pathfindermodel">
  <eClassifiers xsi:type="ecore:EClass" name="PathFinderModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//Section" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trains" upperBound="-1"
        eType="#//Train" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="neighbours" upperBound="4"
        eType="#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rail" eSuperTypes="#//Section"/>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Section"/>
  <eClassifiers xsi:type="ecore:EClass" name="Train">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentlyOn" lowerBound="1"
        eType="#//Section"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
        defaultValueLiteral="0" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goal" lowerBound="1" eType="#//Section"/>
  </eClassifiers>
</ecore:EPackage>
